apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-spole
  namespace: default
  labels:
    team: tbd
spec:
  image: docker.pkg.github.com/{{version}}
  port: 8082
  liveness:
    path: /isalive
  readiness:
    path: /isready
  replicas:
    min: 1
    max: 1
  ingresses:
    - "https://helse-spole.nais.preprod.local"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
