management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus, health, info
      path-mapping:
        prometheus: /internal/metrics

spring:
  application:
    name: spole

server:
  port: 8082