apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spole
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8082
  ingresses:
    - https://spole.nais.preprod.local
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: "/isalive"
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: "/internal/metrics"
  readiness:
    initialDelay: 20
    path: "/isready"
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - mountPath: "/var/run/secrets/nais.io/vault"
        kvPath: "/kv/preprod/fss/spole/default"
      - mountPath: "/var/run/secrets/nais.io/azure"
        kvPath: "/azuread/data/dev/creds/helse-spole"
  webproxy: true
  secureLogs:
    enabled: true
  env:
    - name: AKTORREGISTER_URL
      value: https://app-q1.adeo.no/aktoerregister
    - name: INFOTRYGD_SCOPE
      value: https://trygdeetaten.no/infotrygdsykepenger/.default
    - name: AZURE_TENANT_ID
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
